In [1]:
import pandas as pd

In [2]:
from collections import *

In [3]:
df = pd.read_csv("sales_data.csv")

In [4]:
df.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [8]:
unit_price = df["Unit Price"]

In [9]:
unit_price

0      999.99
1      499.99
2       69.99
3       15.99
4       89.99
        ...
235    159.99
236     90.00
237     10.99
238     55.00
239     29.99
Name: Unit Price, Length: 240, dtype: float64

In [13]:
OrderedDict(unit_price)

OrderedDict([(0, np.float64(999.99)),
             (1, np.float64(499.99)),
             (2, np.float64(69.99)),
             (3, np.float64(15.99)),
             (4, np.float64(89.99)),
             (5, np.float64(29.99)),
             (6, np.float64(2499.99)),
             (7, np.float64(599.99)),
             (8, np.float64(89.99)),
             (9, np.float64(25.99)),
             (10, np.float64(129.99)),
             (11, np.float64(199.99)),
             (12, np.float64(749.99)),
             (13, np.float64(189.99)),
             (14, np.float64(249.99)),
             (15, np.float64(35.99)),
             (16, np.float64(399.99)),
             (17, np.float64(119.99)),
             (18, np.float64(499.99)),
             (19, np.float64(99.99)),
             (20, np.float64(59.99)),
             (21, np.float64(22.99)),
             (22, np.float64(49.99)),
             (23, np.float64(29.99)),
             (24, np.float64(299.99)),
             (25, np.float64(179.99)),
             (26, np.float64(179.99)),
             (27, np.float64(12.99)),
             (28, np.float64(29.99)),
             (29, np.float64(129.99)),
             (30, np.float64(349.99)),
             (31, np.float64(89.99)),
             (32, np.float64(29.99)),
             (33, np.float64(19.99)),
             (34, np.float64(39.99)),
             (35, np.float64(1895.0)),
             (36, np.float64(399.99)),
             (37, np.float64(799.99)),
             (38, np.float64(59.99)),
             (39, np.float64(24.99)),
             (40, np.float64(105.0)),
             (41, np.float64(129.99)),
             (42, np.float64(399.99)),
             (43, np.float64(199.99)),
             (44, np.float64(139.99)),
             (45, np.float64(32.5)),
             (46, np.float64(52.0)),
             (47, np.float64(39.99)),
             (48, np.float64(129.99)),
             (49, np.float64(299.99)),
             (50, np.float64(154.99)),
             (51, np.float64(26.99)),
             (52, np.float64(49.0)),
             (53, np.float64(49.99)),
             (54, np.float64(59.99)),
             (55, np.float64(499.99)),
             (56, np.float64(29.99)),
             (57, np.float64(28.0)),
             (58, np.float64(23.0)),
             (59, np.float64(349.0)),
             (60, np.float64(299.99)),
             (61, np.float64(199.99)),
             (62, np.float64(9.99)),
             (63, np.float64(18.99)),
             (64, np.float64(102.0)),
             (65, np.float64(299.99)),
             (66, np.float64(1199.99)),
             (67, np.float64(219.99)),
             (68, np.float64(59.99)),
             (69, np.float64(10.99)),
             (70, np.float64(78.0)),
             (71, np.float64(129.99)),
             (72, np.float64(1599.99)),
             (73, np.float64(899.99)),
             (74, np.float64(49.99)),
             (75, np.float64(14.99)),
             (76, np.float64(16.0)),
             (77, np.float64(69.99)),
             (78, np.float64(249.99)),
             (79, np.float64(499.99)),
             (80, np.float64(89.99)),
             (81, np.float64(12.99)),
             (82, np.float64(100.0)),
             (83, np.float64(24.99)),
             (84, np.float64(99.99)),
             (85, np.float64(1299.99)),
             (86, np.float64(79.99)),
             (87, np.float64(13.99)),
             (88, np.float64(105.0)),
             (89, np.float64(129.99)),
             (90, np.float64(99.99)),
             (91, np.float64(179.99)),
             (92, np.float64(79.99)),
             (93, np.float64(14.99)),
             (94, np.float64(68.0)),
             (95, np.float64(999.99)),
             (96, np.float64(299.99)),
             (97, np.float64(349.99)),
             (98, np.float64(19.99)),
             (99, np.float64(12.99)),
             (100, np.float64(82.0)),
             (101, np.float64(109.99)),
             (102, np.float64(3899.99)),
             (103, np.float64(349.99)),
             (104, np.float64(39.99)),
             (105, np.float64(10.99)),
             (106, np.float64(6.5)),
             (107, np.float64(399.99)),
             (108, np.float64(229.99)),
             (109, np.float64(159.99)),
             (110, np.float64(14.99)),
             (111, np.float64(18.99)),
             (112, np.float64(15.0)),
             (113, np.float64(229.95)),
             (114, np.float64(249.99)),
             (115, np.float64(299.95)),
             (116, np.float64(49.99)),
             (117, np.float64(16.99)),
             (118, np.float64(14.99)),
             (119, np.float64(249.99)),
             (120, np.float64(599.99)),
             (121, np.float64(89.99)),
             (122, np.float64(12.99)),
             (123, np.float64(14.99)),
             (124, np.float64(30.0)),
             (125, np.float64(199.99)),
             (126, np.float64(499.99)),
             (127, np.float64(399.99)),
             (128, np.float64(98.0)),
             (129, np.float64(8.99)),
             (130, np.float64(36.0)),
             (131, np.float64(39.95)),
             (132, np.float64(1299.99)),
             (133, np.float64(79.99)),
             (134, np.float64(34.99)),
             (135, np.float64(9.99)),
             (136, np.float64(6.8)),
             (137, np.float64(99.95)),
             (138, np.float64(1499.99)),
             (139, np.float64(139.99)),
             (140, np.float64(44.99)),
             (141, np.float64(11.99)),
             (142, np.float64(29.5)),
             (143, np.float64(299.99)),
             (144, np.float64(549.0)),
             (145, np.float64(199.95)),
             (146, np.float64(98.0)),
             (147, np.float64(10.99)),
             (148, np.float64(25.0)),
             (149, np.float64(149.99)),
             (150, np.float64(349.99)),
             (151, np.float64(199.99)),
             (152, np.float64(54.99)),
             (153, np.float64(16.99)),
             (154, np.float64(59.0)),
             (155, np.float64(299.99)),
             (156, np.float64(899.99)),
             (157, np.float64(499.95)),
             (158, np.float64(24.99)),
             (159, np.float64(7.99)),
             (160, np.float64(36.0)),
             (161, np.float64(34.99)),
             (162, np.float64(1199.99)),
             (163, np.float64(199.99)),
             (164, np.float64(29.99)),
             (165, np.float64(8.99)),
             (166, np.float64(16.99)),
             (167, np.float64(49.99)),
             (168, np.float64(699.99)),
             (169, np.float64(139.99)),
             (170, np.float64(34.99)),
             (171, np.float64(9.99)),
             (172, np.float64(29.5)),
             (173, np.float64(699.99)),
             (174, np.float64(49.99)),
             (175, np.float64(49.99)),
             (176, np.float64(14.9)),
             (177, np.float64(11.99)),
             (178, np.float64(34.0)),
             (179, np.float64(146.0)),
             (180, np.float64(649.99)),
             (181, np.float64(399.99)),
             (182, np.float64(59.99)),
             (183, np.float64(12.99)),
             (184, np.float64(190.0)),
             (185, np.float64(499.95)),
             (186, np.float64(399.0)),
             (187, np.float64(199.0)),
             (188, np.float64(34.99)),
             (189, np.float64(10.99)),
             (190, np.float64(18.0)),
             (191, np.float64(169.95)),
             (192, np.float64(199.99)),
             (193, np.float64(199.95)),
             (194, np.float64(179.99)),
             (195, np.float64(11.99)),
             (196, np.float64(125.0)),
             (197, np.float64(449.99)),
             (198, np.float64(179.0)),
             (199, np.float64(99.95)),
             (200, np.float64(59.99)),
             (201, np.float64(14.99)),
             (202, np.float64(52.0)),
             (203, np.float64(399.99)),
             (204, np.float64(299.99)),
             (205, np.float64(379.99)),
             (206, np.float64(98.0)),
             (207, np.float64(16.99)),
             (208, np.float64(79.0)),
             (209, np.float64(129.0)),
             (210, np.float64(749.99)),
             (211, np.float64(169.99)),
             (212, np.float64(9.9)),
             (213, np.float64(10.99)),
             (214, np.float64(29.0)),
             (215, np.float64(349.99)),
             (216, np.float64(2399.0)),
             (217, np.float64(449.99)),
             (218, np.float64(49.99)),
             (219, np.float64(12.99)),
             (220, np.float64(27.0)),
             (221, np.float64(599.99)),
             (222, np.float64(49.99)),
             (223, np.float64(229.99)),
             (224, np.float64(44.99)),
             (225, np.float64(26.99)),
             (226, np.float64(6.7)),
             (227, np.float64(149.95)),
             (228, np.float64(169.0)),
             (229, np.float64(599.0)),
             (230, np.float64(64.99)),
             (231, np.float64(9.99)),
             (232, np.float64(24.0)),
             (233, np.float64(32.95)),
             (234, np.float64(299.0)),
             (235, np.float64(159.99)),
             (236, np.float64(90.0)),
             (237, np.float64(10.99)),
             (238, np.float64(55.0)),
             (239, np.float64(29.99))])

In [14]:
d = defaultdict()